"""initial schema

Revision ID: 9b64667d664e
Revises:
Create Date: 2026-02-08 02:10:46.460438

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "9b64667d664e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
